replacing with another zgrep

diff --git a/programs/zstdgrep b/programs/zstdgrep
--- a/programs/zstdgrep
+++ b/programs/zstdgrep
@@ -1,143 +1,225 @@
 #!/bin/sh
-#
-# Copyright (c) 2003 Thomas Klausner.
-#
-# Redistribution and use in source and binary forms, with or without
-# modification, are permitted provided that the following conditions
-# are met:
-# 1. Redistributions of source code must retain the above copyright
-#    notice, this list of conditions and the following disclaimer.
-# 2. Redistributions in binary form must reproduce the above copyright
-#    notice, this list of conditions and the following disclaimer in the
-#    documentation and/or other materials provided with the distribution.
-#
-# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
-# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
-# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
-# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
-# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
-# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
-# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-grep=${GREP:-grep}
-zcat=${ZCAT:-zstdcat}
+# zgrep -- a wrapper around a grep program that decompresses files as needed
+# Adapted from a version sent by Charles Levert <charles@comm.polymtl.ca>
 
-endofopts=0
-pattern_found=0
-grep_args=""
-hyphen=0
-silent=0
+# Copyright (C) 1998, 2001, 2002, 2006, 2007, 2009, 2010 Free Software
+# Foundation
 
-prog=${0##*/}
+# Copyright (C) 1993 Jean-loup Gailly
 
-# handle being called 'zegrep' or 'zfgrep'
-case $prog in
-    *egrep*) prog=zegrep; grep_args='-E';;
-    *fgrep*) prog=zfgrep; grep_args='-F';;
-    *)       prog=zstdgrep;;
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 3 of the License, or
+# (at your option) any later version.
+
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+
+# You should have received a copy of the GNU General Public License along
+# with this program; if not, write to the Free Software Foundation, Inc.,
+# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+
+bindir='/usr/bin'
+case $1 in
+--__bindir) bindir=${2?}; shift; shift;;
 esac
+PATH=$bindir:$PATH
 
-all_patterns() {
-    local part IFS=\'; set -- $1""
-    unset _patterns
-    for part do
-        _patterns=${_patterns+$_patterns\'\\\'\'}$part
-        pattern_found=$((pattern_found+1))
-    done
-}
+zcat=${ZCAT:-zstdcat}
+grep='${GREP-grep}'
 
-# skip all options and pass them on to grep taking care of options
-# with arguments, and if -e was supplied
+version='zgrep (gzip) 1.5
+Copyright (C) 2010-2012 Free Software Foundation, Inc.
+This is free software.  You may redistribute copies of it under the terms of
+the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
+There is NO WARRANTY, to the extent permitted by law.
 
-while [ "$#" -gt 0 ] && [ "${endofopts}" -eq 0 ]; do
-    case "$1" in
-    # from GNU grep-2.5.1 -- keep in sync!
-        -[ABCDXdefm])
-            if [ "$#" -lt 2 ]; then
-                printf '%s: missing argument for %s flag\n' "${prog}" "$1" >&2
-                exit 1
-            fi
-            case "$1" in
-                -ef)
-                    pattern=""
-                    pattern_found=1
-                    all_patterns "$2"
-                    grep_args="${grep_args} $1 ${_patterns}"
-                    ;;
-                *)
-                    grep_args="${grep_args} $1 $2"
-                    ;;
-            esac
-            shift 2
-            ;;
-        --regexp)
-            pattern=""
-            pattern_found=1
-            all_patterns "$2"
-            grep_args="${grep_args} $1 ${_patterns}"
-            shift 2
-            ;;
-        --)
-            shift
-            endofopts=1
-            ;;
-        -)
-            hyphen=1
-            shift
-            ;;
-        -h)
-            silent=1
-            shift
-            ;;
-        -*)
-            grep_args="${grep_args} $1"
-            shift
-            ;;
-        *)
-            # pattern to grep for
-            endofopts=1
-            ;;
+Written by Jean-loup Gailly.'
+
+usage="Usage: $0 [OPTION]... [-e] PATTERN [FILE]...
+Look for instances of PATTERN in the input FILEs, using their
+uncompressed contents if they are compressed.
+
+OPTIONs are the same as for 'grep', except that the following 'grep'
+options are not supported: --dereference-recursive (-R), --directories (-d),
+--exclude, --exclude-from, --exclude-dir, --include, --null (-Z),
+--null-data (-z), and --recursive (-r).
+
+Report bugs to <bug-gzip@gnu.org>."
+
+# sed script to escape all ' for the shell, and then (to handle trailing
+# newlines correctly) append ' to the last line.
+escape='
+  s/'\''/'\''\\'\'''\''/g
+  $s/$/'\''/
+'
+operands=
+have_pat=0
+files_with_matches=0
+files_without_matches=0
+no_filename=0
+with_filename=0
+
+while test $# -ne 0; do
+  option=$1
+  shift
+  optarg=
+
+  case $option in
+  (-[0123456789EFGHIKLPRTUVZabchilnoqrsuvwxyz]?*)
+    arg2=-\'$(expr "X$option" : 'X-.[0-9]*\(.*\)' | sed "$escape")
+    eval "set -- $arg2 "'${1+"$@"}'
+    option=$(expr "X$option" : 'X\(-.[0-9]*\)');;
+  (--binary-*=* | --[lm]a*=* | --reg*=*)
+    ;;
+  (-[ABCDXdefm] | binary-* | --file | --[lm]a* | --reg*)
+    case ${1?"$option option requires an argument"} in
+    (*\'*)
+      optarg=" '"$(printf '%s\n' "$1" | sed "$escape");;
+    (*)
+      optarg=" '$1'";;
     esac
+    shift;;
+  (-f?*\'*)
+    optarg=" '"$(expr "X$option" : 'X-f\(.*\)' | sed "$escape")
+    option=-f;;
+  (-f?*)
+    optarg=" '"$(expr "X$option" : 'X-f\(.*\)')\'
+    option=-f;;
+  (--file=*\'*)
+    optarg=" '"$(expr "X$option" : 'X--file=\(.*\)' | sed "$escape")
+    option=--file;;
+  (--file=*)
+    optarg=" '"$(expr "X$option" : 'X--file=\(.*\)')\'
+    option=--file;;
+  (--)
+    break;;
+  (-?*)
+    ;;
+  (*)
+    case $option in
+    (*\'*)
+      operands="$operands '"$(printf '%s\n' "$option" | sed "$escape");;
+    (*)
+      operands="$operands '$option'";;
+    esac
+    ${POSIXLY_CORRECT+break}
+    continue;;
+  esac
+
+  case $option in
+  (-[drRzZ] | --di* | --exc* | --inc* | --rec* | --nu*)
+    printf >&2 '%s: %s: option not supported\n' "$0" "$option"
+    exit 2;;
+  (-e* | --reg*)
+    have_pat=1;;
+  (-f | --file)
+    # The pattern is coming from a file rather than the command-line.
+    # If the file is actually stdin then we need to do a little
+    # magic, since we use stdin to pass the gzip output to grep.
+    # Turn the -f option into an -e option by copying the file's
+    # contents into OPTARG.
+    case $optarg in
+    (" '-'" | " '/dev/stdin'" | " '/dev/fd/0'")
+      option=-e
+      optarg=" '"$(sed "$escape") || exit 2;;
+    esac
+    have_pat=1;;
+  (--h | --he | --hel | --help)
+    echo "$usage" || exit 2
+    exit;;
+  (-H | --wi | --wit | --with | --with- | --with-f | --with-fi \
+  | --with-fil | --with-file | --with-filen | --with-filena | --with-filenam \
+  | --with-filename)
+    with_filename=1
+    continue;;
+  (-l | --files-with-*)
+    files_with_matches=1;;
+  (-L | --files-witho*)
+    files_without_matches=1;;
+  (-h | --no-f*)
+    no_filename=1;;
+  (-V | --v | --ve | --ver | --vers | --versi | --versio | --version)
+    echo "$version" || exit 2
+    exit;;
+  esac
+
+  case $option in
+  (*\'?*)
+    option=\'$(printf '%s\n' "$option" | sed "$escape");;
+  (*)
+    option="'$option'";;
+  esac
+
+  grep="$grep $option$optarg"
 done
 
-# if no -e option was found, take next argument as grep-pattern
-if [ "${pattern_found}" -lt 1 ]; then
-    if [ "$#" -ge 1 ]; then
-        pattern="$1"
-        shift
-    elif [ "${hyphen}" -gt 0 ]; then
-        pattern="-"
-    else
-        printf '%s: missing pattern\n' "${prog}" >&2
-        exit 1
-    fi
+eval "set -- $operands "'${1+"$@"}'
+
+if test $have_pat -eq 0; then
+  case ${1?"missing pattern; try \`$0 --help' for help"} in
+  (*\'*)
+    grep="$grep -- '"$(printf '%s\n' "$1" | sed "$escape");;
+  (*)
+    grep="$grep -- '$1'";;
+  esac
+  shift
 fi
 
-EXIT_CODE=0
-# call grep ...
-if [ "$#" -lt 1 ]; then
-    # ... on stdin
-    # shellcheck disable=SC2086
-    eval "${zcat} -fq - | ${grep} ${grep_args} -- ${pattern}"
-    EXIT_CODE=$?
-else
-    # ... on all files given on the command line
-    if [ "${silent}" -lt 1 ] && [ "$#" -gt 1 ]; then
-        grep_args="-H ${grep_args}"
-    fi
-    while [ "$#" -gt 0 ]; do
-        # shellcheck disable=SC2086
-        if [ $pattern_found -eq 2 ]; then
-            eval "${zcat} -fq -- \"$1\" | ${grep} --label=\"${1}\" ${grep_args} --"
-        else
-            eval "${zcat} -fq -- \"$1\" | ${grep} --label=\"${1}\" ${grep_args} ${pattern} --"
+if test $# -eq 0; then
+  set -- -
+fi
+
+exec 3>&1
+res=0
+
+for i
+do
+  # Fail if gzip or grep (or sed) fails.
+  gzip_status=$(
+    exec 5>&1
+    ($zcat -- "$i" 5>&-; echo $? >&5) 3>&- |
+    if test $files_with_matches -eq 1; then
+      eval "$grep" >/dev/null && { printf '%s\n' "$i" || exit 2; }
+    elif test $files_without_matches -eq 1; then
+      eval "$grep" >/dev/null || {
+        r=$?
+        if test $r -eq 1; then
+          printf '%s\n' "$i" || r=2
         fi
-        [ "$?" -ne 0 ] && EXIT_CODE=1
-        shift
-    done
-fi
+        exit $r
+      }
+    elif test $with_filename -eq 0 &&
+         { test $# -eq 1 || test $no_filename -eq 1; }; then
+      eval "$grep"
+    else
+      case $i in
+      (*'
+'* | *'&'* | *'\'* | *'|'*)
+        i=$(printf '%s\n' "$i" |
+            sed '
+              $!N
+              $s/[&\|]/\\&/g
+              $s/\n/\\n/g
+            ');;
+      esac
+      sed_script="s|^|$i:|"
 
-exit "${EXIT_CODE}"
+      # Fail if grep or sed fails.
+      r=$(
+        exec 4>&1
+        (eval "$grep" 4>&-; echo $? >&4) 3>&- | sed "$sed_script" >&3 4>&-
+      ) && exit $r
+      r=$?
+      test 1 -lt $r && exit $r || exit 2
+    fi >&3 5>&-
+  )
+  r=$?
+  test 128 -lt $r && exit $r
+  test "$gzip_status" -eq 0 || test "$gzip_status" -eq 2 || r=2
+  test $res -lt $r && res=$r
+done
+exit $res
